title: 'Solarize'
default_lang: 'en'
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
footer:
  social:
    title: Connect with us
    byline: In posuere eleifend odio quisque semper.
    items:
      -
        title: YouTube
        icon: fa fa-youtube-play
        url: '#'
      -
        title: Facebook
        icon: fa fa-facebook
        url: '#'
      -
        title: Tickets
        # icon: fa fa-ticket
        icon: fa fa-tags
        url: '#'
  legal:
    attribution:
      title: 'Attribution'
      id: '#attribution'
    privacy:
      title: 'Privacy Policy'
      id: '#privacy'
    notice:
      title: 'Legal Notice'
    #  id: ''
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
